Delete Ubyte Byte replace by int and not check int8_t size
Sdpierret/pyopendds pull request #27
Opened 2022-03-30 10:21 UTC by swolferDF

remove  Ubyte and Byte 
replace by int 

-> testing send Image with seq octet : c++ to python / python to c++

2022-04-04 07:17 UTC, Sdpierret requested changes

2022-04-04 07:17 UTC, Sdpierret commented on pyopendds/util.py
> +#     @staticmethod
please remove all the commented codes

2022-04-04 07:24 UTC, swolferDF commented on pyopendds/util.py
> +#     @staticmethod
done

2022-04-07 09:37 UTC, Sdpierret approved these changes

2022-04-07 09:39 UTC, Sdpierret commented
resolve #20

2022-05-12 08:29 UTC, Sdpierret commented
@swolferDF je viens de "rebase" la branche sur le master 3.20.

je te laisse relire :)

2022-05-12 08:29 UTC, Sdpierret commented
@swolferDF je viens de "rebase" la branche sur le master 3.20.

je te laisse relire :)

2022-05-12 09:21 UTC, sfaucherDF approved these changes

2022-05-12 09:31 UTC, p-e-s approved these changes

2022-05-12 10:11 UTC, merged