Dev dcps info report discovery
Sdpierret/pyopendds pull request #7
Opened 2021-11-23 16:01 UTC by swolferDF

- change init_opendds with config args 
-  change on init_opendds_impl for default_rtps config 
- shutdown particpant factory when there are no more particpants.

2021-11-24 09:38 UTC, Sdpierret requested changes
some cleanup do do

2021-11-24 09:38 UTC, Sdpierret commented on pyopendds/DomainParticipant.py
> +
useless line added

2021-11-24 09:38 UTC, Sdpierret commented on pyopendds/DomainParticipant.py
> +
remove trailing line

2021-11-24 09:38 UTC, Sdpierret commented on pyopendds/init_opendds.py
> +    # args = list(sys.argv[1:])
remove if unused

2021-11-24 09:38 UTC, Sdpierret commented on tests/basic_test/publisher.py
> +        # print(domain)
remove if unused

2021-11-24 09:48 UTC, swolferDF commented on tests/basic_test/publisher.py
> +        # print(domain)
done

2021-12-06 13:47 UTC, Sdpierret commented on pyopendds/DomainParticipant.py
> -
python format standard : 2 lines before a class definition

2021-12-06 13:56 UTC, Sdpierret requested changes
mainly to avoid adding more "unwanted" change in case of push to mainline repository

2021-12-06 13:56 UTC, Sdpierret commented on pyopendds/DomainParticipant.py
> +        return Publisher(self, qos)
no new line ad end of file

2021-12-06 13:56 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +    if (!participant){
why reformat
indentation missing
please keep old format

2021-12-08 14:11 UTC, swolferDF commented on pyopendds/DomainParticipant.py
> -
done

2021-12-08 14:11 UTC, swolferDF commented on pyopendds/DomainParticipant.py
> +        return Publisher(self, qos)
done

2021-12-08 14:11 UTC, swolferDF commented on pyopendds/ext/_pyopendds.cpp
> +    if (!participant){
done

2021-12-09 08:48 UTC, Sdpierret approved these changes

2021-12-09 08:57 UTC, Sdpierret commented
please resolve the conflit before merge

2021-12-09 09:06 UTC, merged