find problem segfaults
Sdpierret/pyopendds pull request #8
Opened 2021-12-01 10:57 UTC by swolferDF

Find segfaults finishing programme with writer and reader 
In function updatewriterqos and updatereaderqos put args pyobject instead of Ref on c++ code

2021-12-01 13:09 UTC, p-e-s commented on pyopendds/ext/_pyopendds.cpp
> +    std::cerr << "get durability" << std::endl;
Can you remove this remaining log?

2021-12-01 13:14 UTC, swolferDF commented on pyopendds/ext/_pyopendds.cpp
> +    std::cerr << "get durability" << std::endl;
done

2021-12-06 14:06 UTC, Sdpierret requested changes
Tu vas me haïr :/

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/Publisher.py
> +        print("[pyopendds] creat datawriter")
logs ?

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/Publisher.py
> +        # self.writers.append(writer)
dead code in comment

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +
trailing whitespaces

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +    // participant_factory->delete_participant(participant);
dead code in comment

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> + bool update_writer_qos(PyObject* pyQos, DDS::DataWriterQos &qos)
space before "bool"

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +
trailing whitespace

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +
trailing whitespace

2021-12-06 14:06 UTC, Sdpierret commented on pyopendds/ext/_pyopendds.cpp
> +
trailing whitespace

2021-12-06 14:45 UTC, p-e-s approved these changes
Ok for me.

2021-12-06 15:05 UTC, swolferDF commented on pyopendds/Publisher.py
> +        # self.writers.append(writer)
done

2021-12-06 15:06 UTC, swolferDF commented on pyopendds/ext/_pyopendds.cpp
> +    // participant_factory->delete_participant(participant);
done

2021-12-06 15:07 UTC, swolferDF commented on pyopendds/ext/_pyopendds.cpp
> + bool update_writer_qos(PyObject* pyQos, DDS::DataWriterQos &qos)
done

2021-12-07 12:36 UTC, Sdpierret approved these changes

2021-12-07 12:36 UTC, merged