fix wrong counting of PyObject
Sdpierret/pyopendds pull request #9
Opened 2021-12-10 12:31 UTC by PaulRousse

2021-12-10 15:41 UTC, p-e-s approved these changes
Ok for me. I let the experts check it.

2021-12-10 16:26 UTC, Sdpierret reviewed
only one question

2021-12-10 16:26 UTC, Sdpierret commented on pyopendds/dev/include/pyopendds/basictype.hpp
> +        Py_INCREF(py);
the REF is never released ?

2021-12-10 16:28 UTC, Sdpierret reviewed
only one question

2021-12-10 16:49 UTC, Sdpierret requested changes

2021-12-10 16:49 UTC, Sdpierret commented on pyopendds/dev/include/pyopendds/basictype.hpp
> +        Py_INCREF(py);
https://docs.python.org/3/c-api/bool.html

maybe use `PyBool_FromLong(cpp)` and remove the `Py_INCREF()`

2021-12-14 07:43 UTC, Sdpierret approved these changes

2021-12-14 07:43 UTC, merged